{
  description = "ArMonarch's NixOS Configuration flake";

  inputs = {
    # NixOS official package source, using the nixos-25.05 branch
    nixpkgs.url = "github:nixos/nixpkgs/nixos-25.05";
    # NixOS official package source, using the nixos-unstable branch
    nixpkgs-unstable.url = "github:nixos/nixpkgs/nixos-unstable";
    # Stylix theming frammwork.
    stylix = {
      url = "github:nix-community/stylix/release-25.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    # Add Home-Manager as NixOS Module
    home-manager = {
      url = "github:nix-community/home-manager/release-25.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    {
      nixpkgs,
      nixpkgs-unstable,
      ...
    }@inputs:
    {
      nixosConfigurations = {
        # The 'frenzfries' profile serves as the default NixOS configuration.
        # It provides a reliable, self-contained setup defined in ./hosts/frenzfries/default.nix,
        # with no external dependencies. This profile is based on the initial configuration
        # generated by `nixos-generate-config` with needed terminal and shell installed and configured.
        #
        # IMPORTANT: To ensure correct hardware support, always replace
        # ./profiles/frenzfries/hardware-configuration.nix with the latest output from `nixos-generate-config`.
        #
        # This profile acts as a fallback: if any other configuration fails, 'frenzfries' is
        # our stable, working baseline.
        frenzfries =
          let
            host = "frenzfries";
            system = "x86_64-linux";
          in
          nixpkgs.lib.nixosSystem {
            inherit system;
            specialArgs = {
              inherit host;
              inherit nixpkgs;
              inherit inputs;
            };
            modules = [
              ./profiles/frenzfries
            ];
          };

        lunar =
          let
            host = "frenzfries";
            system = "x86_64-linux";
          in
          nixpkgs.lib.nixosSystem {
            inherit system;
            specialArgs = {
              inherit host;
              inherit system;
              inherit inputs;
              inherit nixpkgs;
              inherit nixpkgs-unstable;
            };
            modules = [
              ./profiles/lunar/default.nix
            ];
          };
      };
    };
}
